import { useGLTF } from "@react-three/drei";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export default function Pine(props: any) {
  const { nodes, materials } = useGLTF("/pine/pine.gltf");
  return (
    <group {...props} dispose={null}>
      <lineSegments
        // TODO: fix the type errors instead of using ts-ignore
        //@ts-ignore
        geometry={nodes.model002_1.geometry}
        material={materials["place_holder.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        //@ts-ignore
        geometry={nodes.model002_2.geometry}
        material={materials["place_holder.003"]}
      />
    </group>
  );
}

useGLTF.preload("/pine.gltf");
